### ISSUE TITLE
The clear button can't be removed after state change from enabled to disabled

### ISSUE THREAD

**Issue by yya109** [maxschuster/Vaadin-SignatureField#8]
If I set clearButtonEnabled=true, a clear button will be displayed at the top on the right of the field. The button should disappear if the signiture field goes readonly or I set clearButtonEnabled=false again. But this doesn't work.
This problem can be reproduced in the demo application.

The onStateChange function of SignatureFieldExtension.js tries to remove the clear button(line 269):
...
} else if ((readOnly || !state.clearButtonEnabled) && this.clearButton) {
            var clearButton = this.clearButton;
            parent.removeElement(clearButton);
            this.clearButton = null;
        }
...
but the method removeElement doesn't exist.
stacktrace:
ConsoleLogger.java:32 Error sending state change events
EQq_g$ @ ConsoleLogger.java:32
Nkq_g$ @ SimpleConsoleLogHandler.java:36
_jq_g$ @ Logger.java:312
$jq_g$ @ Logger.java:302
wkq_g$ @ Logger.java:236
fGe_g$ @ MessageHandler.java:766
$Fe_g$ @ MessageHandler.java:484
o7d_g$ @ ApplicationConfiguration.java:662
wFe_g$ @ MessageHandler.java:1501
xFe_g$ @ MessageHandler.java:246
bJe_g$ @ XhrConnection.java:166
qkc_g$ @ Request.java:250
ylc_g$ @ RequestBuilder.java:412
(anonymous) @ XMLHttpRequest.java:329
qJ_g$ @ Impl.java:239
tJ_g$ @ Impl.java:291
(anonymous) @ Impl.java:77
XMLHttpRequest.send (async)
n5d_g$ @ XMLHttpRequest.java:305
clc_g$ @ RequestBuilder.java:418
llc_g$ @ RequestBuilder.java:242
JIe_g$ @ XhrConnection.java:206
SGe_g$ @ MessageSender.java:185
RGe_g$ @ MessageSender.java:168
FGe_g$ @ MessageSender.java:131
TGe_g$ @ MessageSender.java:90
UHe_g$ @ ServerRpcQueue.java:202
fL_g$ @ SchedulerImpl.java:50
LK_g$ @ SchedulerImpl.java:183
FK_g$ @ SchedulerImpl.java:279
uJ_g$ @ Impl.java:315
tJ_g$ @ Impl.java:306
(anonymous) @ Impl.java:77
ConsoleLogger.java:55 Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : d.removeElement is not a function
ConsoleLogger.java:32 Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : d.removeElement is not a function
    at Ejc_g$.fA_g$ [as createError_0_g$] (Throwable.java:121)
    at Ejc_g$.pA_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
    at Ejc_g$._z_g$ (Throwable.java:74)
    at Ejc_g$.FA_g$ (Exception.java:33)
    at Ejc_g$.NA_g$ (RuntimeException.java:33)
    at Ejc_g$.xjc_g$ (UmbrellaException.java:65)
    at new Ejc_g$ (UmbrellaException.java:26)
    at sic_g$.vic_g$ [as fireEvent_2_g$] (HandlerManager.java:129)
    at hhe_g$.Cge_g$ [as fireEvent_2_g$] (AbstractConnector.java:240)
    at WFe_g$.fGe_g$ [as sendStateChangeEvents_0_g$] (MessageHandler.java:764)
    at WFe_g$.$Fe_g$ [as execute_1_g$] (MessageHandler.java:484)
    at o7d_g$ (ApplicationConfiguration.java:662)
    at hFe_g$.wFe_g$ [as handleJSON_0_g$] (MessageHandler.java:1501)
    at hFe_g$.xFe_g$ [as handleMessage_0_g$] (MessageHandler.java:246)
    at _Ie_g$.bJe_g$ [as onResponseReceived_0_g$] (XhrConnection.java:166)
    at nkc_g$.qkc_g$ [as fireOnResponseReceived_0_g$] (Request.java:250)
    at xlc_g$.ylc_g$ [as onReadyStateChange_0_g$] (RequestBuilder.java:412)
    at XMLHttpRequest.<anonymous> (XMLHttpRequest.java:329)
    at qJ_g$ (Impl.java:239)
    at tJ_g$ (Impl.java:291)
    at XMLHttpRequest.<anonymous> (Impl.java:77)

**Comment by maxschuster** [comment]
Thank you for reporting. It should work with version 2.0.1.
